/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minivm;
import minivm.Computer;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.util.List;

import static org.junit.Assert.*;

public class UnitTest {
    //Test if instruction is correcly cut by the parser
    @Test public void correctLineNumbers(){
        Computer computer = new Computer();
        File file = new File("file_exemples/one.txt");
        computer.set_file(file);
        List<List> instructions_list = computer.get_instructions();
        assertEquals(4, instructions_list.size());
        assertEquals("mov", instructions_list.get(0).get(0) );
        assertEquals("65", instructions_list.get(1).get(1));

    }


}
